### ISSUE TITLE
Some real sources are masked while the jump step with `expand_large_events=True` in the JWST pipeline does not.

### ISSUE THREAD

**Issue by izkgao** [mpi-astronomy/snowblind#2]
I found that in this specific image sets `jw01837004001_04201_00001` and `jw01837004001_04201_00002` (F356W, four images) snowblind does not work well. The centers of many sources are masked. But this does not happen in other images I have reviewed. Only in this image. And this problem does not happen in the JWST Stage-1 pipeline with the argument of the `jump` step `expand_large_events` set to True.

**Download link for the file**
[https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00001_nrcalong_uncal.fits](https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00001_nrcalong_uncal.fits)
[https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00001_nrcblong_uncal.fits](https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00001_nrcblong_uncal.fits)
[https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00002_nrcalong_uncal.fits](https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00002_nrcalong_uncal.fits)
[https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00002_nrcblong_uncal.fits](https://mast.stsci.edu/api/v0.1/Download/file?uri=mast:JWST/product/jw01837004001_04201_00002_nrcblong_uncal.fits)

**The code to reproduce this problem and the images below**
```python
# jwst version: 1.12.5
# CRDS context: jwst_1166.pmap
from jwst.pipeline import Detector1Pipeline, Image2Pipeline

file = 'jw01837004001_04201_00002_nrcalong_uncal.fits'

# Pipeline with `expand_large_events` set to True
args = {'persistence': {'save_trapsfilled': False},
        'jump': {'skip': False,
        'expand_large_events': True}}
rate_pipeline = Detector1Pipeline.call(file, steps=args)
cal_pipeline = Image2Pipeline.call(rate_pipeline, steps={'resample': {'skip': True}})

# Snowblind
args = {'persistence': {'save_trapsfilled': False},
        'jump': {'skip': False,
        'expand_large_events': False,
        'post_hooks': ['snowblind.SnowblindStep']}}
rate_snowblind = Detector1Pipeline.call(file, steps=args)
cal_snowblind = Image2Pipeline.call(rate_snowblind, steps={'resample': {'skip': True}})
```

![image](https://github.com/mpi-astronomy/snowblind/assets/16133788/9fd9897a-4af5-48be-b47d-82fba3dceccc)
![image](https://github.com/mpi-astronomy/snowblind/assets/16133788/cfc87b12-d64c-46f7-aa9f-4799d65e63d3)

**Comment by jdavies-st** [comment]
Thanks for the feedback!  I'll run the data on my end and see what is happening.

**Comment by jdavies-st** [comment]
Hi @izkgao, looking at the 3D cube after `jump` step, but before ramp fitting is a good diagnostic.  Loading up the SCI and DQ arrays shows that with the default settings, the standard pipeline is flagging the cores of the galaxies as JUMP_DET.  This is very surprising, as they are not jumps, and are not close to the saturation limit either.  Relaxing the default `detection_threshold` from 4 sigma to 8 sigma in the jump step doesn't improve this.  Surprising!

So this means there's something seriously wrong with the ramps for these datasets.

Looking at the headers:

```
$ fitsheader *_rate.fits | grep VISITSTA
VISITSTA= 'UNSUCCESSFUL'       / Status of a visit                              
VISITSTA= 'UNSUCCESSFUL'       / Status of a visit                              
VISITSTA= 'UNSUCCESSFUL'       / Status of a visit                              
VISITSTA= 'UNSUCCESSFUL'       / Status of a visit
```

Ominous. This implies something is wrong, possibly with the pointing stability during these exposures.  Looking at the shapes of the galaxies, it really does look like there's bad pointing stability.  If you blink through the groups in the _jump files, you can see that the stars and galaxies in the field move about and smear.

We can confirm that this is the problem by looking at the fine guidance sensor (FGS) data using `spelunker` (see https://github.com/GalagaBits/JWST-FGS-Spelunker).

And sure enough there's both small and large swings in counts during each of the 2 exposures (using the EXPSTART and EXPEND header keywords in our data to find the location in the `spelunker` time series)

jw01837004001_04201_00001
![Screenshot 2023-12-13 at 11 26 14](https://github.com/mpi-astronomy/snowblind/assets/17088869/444030e8-9a60-4826-b638-213bfdcec3bf)

And really big movements in the 2nd!

jw01837004001_04201_00002
![Screenshot 2023-12-13 at 11 26 55](https://github.com/mpi-astronomy/snowblind/assets/17088869/903495d2-e36d-4fd2-9ec1-9ca2ef3aece3)

You can do more investigation using `spelunker` if you like, but it's pretty obvious looking at stars blinking through each group in the _jump files.

You can investigate if a report was filed with STScI on these.  Here's the visit status info

https://www.stsci.edu/jwst/science-execution/program-information?id=1837

```xml
<visit observation="4" visit="1">
<status>Failed</status>
<dataStatus>Archived</dataStatus>
<target>COSMOS-2</target>
<configuration>MIRI Imaging</configuration>
<hours>1.95</hours>
<startTime>Dec 26, 2022 18:49:09</startTime>
<endTime>Dec 26, 2022 20:35:57</endTime>
<repeatedBy>
<program>1837</program>
<observation>26</observation>
<visit>1</visit>
<problemID>88654</problemID>
</repeatedBy>
</visit>
```

And sure enough it is marked as failed.

**Comment by jdavies-st** [comment]
You can actually see the movement really well in the _uncal files by looking at stars.  Here's animated GIFs made cycling through the groups of the _uncal for each exposure (NRCALONG).

jw01837004001_04201_00001
![jw01837004001_04201_00001_nrcalong_uncal](https://github.com/mpi-astronomy/snowblind/assets/17088869/9ebfe473-b4f0-4d75-b77d-499b000c6b4a)

jw01837004001_04201_00002
![jw01837004001_04201_00002_nrcalong_uncal](https://github.com/mpi-astronomy/snowblind/assets/17088869/7bb6b541-d731-4e48-b0f1-b8be28a6401e)

**Comment by jdavies-st** [comment]
So given the input data is junk, I'm going to close this issue.  Feel free to comment further if you like.  Hopefully this field gets (or already got) re-observed!  🤞
